sonar.projectKey=chmjkb_projektowanie-obiektowe-2026
sonar.organization=chmjkb

sonar.projectName=projektowanie-obiektowe-2026
sonar.sources=.

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.gradle/**,**/.kotlin/**,**/vendor/**,**/LAB4/weather-app,**/LAB4/weather.db,**/*.jar
